version: "3.1"
services:

  redis:
    container_name: redis_vesoul
    image: redis

  mysql:
    image: mysql:8
    container_name: db_vesoul
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=toortoor
      - MYSQL_DATABASE=vesoul
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toortoor
    ports:
      - "8082:3306"

  web:
    container_name: web_vesoul
    image: nginx:latest
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    container_name: php_vesoul
    build: docker/php
    volumes:
      - .:/application:cached
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - redis